server:
  port: 8092
spring:
  application:
    name: HOTELSERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8094/eureka