server:
  port: 8761
spring:
  main:
    banner-mode: OFF
  application:
    name: ServiceRegistry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false