server:
  port: 8091

spring:
  application:
    name: USERSERVICE
  config:
    import: optional:configserver:http://localhost:8095
  cloud:
    discovery:
      enabled: true
    openfeign:
      client:
        config:
          # Default Feign client configuration
          default:
            connectTimeout: 1000  # Connection timeout in milliseconds
            readTimeout: 5000     # Read timeout in milliseconds
            loggerLevel: full     # Full logging level for Feign requests

          # Specific Feign client configuration for UserService
          RATINGSERVICE:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: BASIC

          # Specific Feign client configuration for HotelService
          HOTELSERVICE:
            connectTimeout: 3000
            readTimeout: 6000
            loggerLevel: basic

  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect

# actuator config
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - circuitbreakers
  health:
    circuitbreakers:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

# resilience4j config
resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50 # If 50% of the calls in the sliding window fail, the circuit breaker transitions to an open state.
        minimumNumberOfCalls: 5 # The circuit breaker will only evaluate failure rates after receiving at least 5 calls.
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      userServiceRetry:
        maxAttempts: 2
        waitDuration: 2s
  ratelimiter:
    instances:
      userServiceRateLimiter:
        timeoutDuration: 5s
        limitForPeriod: 2
        limitRefreshPeriod: 2s