server:
  port: 8091

spring:
  application:
    name: USERSERVICE
  config:
    import: optional:configserver:http://localhost:8095
  cloud:
    discovery:
      enabled: true
    openfeign:
      client:
        config:
          # Default Feign client configuration
          default:
            connectTimeout: 1000  # Connection timeout in milliseconds
            readTimeout: 5000     # Read timeout in milliseconds
            loggerLevel: full     # Full logging level for Feign requests

          # Specific Feign client configuration for UserService
          RATINGSERVICE:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: BASIC

          # Specific Feign client configuration for HotelService
          HOTELSERVICE:
            connectTimeout: 3000
            readTimeout: 6000
            loggerLevel: basic

  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect