server:
  port: 8091

spring:
  cloud:
    discovery:
      enabled: true
    openfeign:
      client:
        config:
          # Default Feign client configuration
          default:
            connectTimeout: 1000  # Connection timeout in milliseconds
            readTimeout: 5000     # Read timeout in milliseconds
            loggerLevel: full     # Full logging level for Feign requests

          # Specific Feign client configuration for UserService
          RATINGSERVICE:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: BASIC

          # Specific Feign client configuration for HotelService
          HOTELSERVICE:
            connectTimeout: 3000
            readTimeout: 6000
            loggerLevel: basic

  application:
    name: USERSERVICE
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka