server:
  port: 8093

spring:
  main:
    banner-mode: OFF
  application:
    name: RATINGSERVICE
  config:
    import: optional:configserver:http://localhost:8095
  data:
    mongodb:
      uri: mongodb+srv://ankushpaul199:8EHD98gyNA3uMANw@cluster0.3mmez.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: microservice